# Generated by Django 5.2.7 on 2026-02-17 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPlantFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('tonnes_fed', models.FloatField(help_text='Tonnes supplied to plant today')),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.IntegerField()),
                ('hg_tonnes', models.FloatField(default=0)),
                ('hg_grade', models.FloatField(default=0)),
                ('mg_tonnes', models.FloatField(default=0)),
                ('mg_grade', models.FloatField(default=0)),
                ('lg_tonnes', models.FloatField(default=0)),
                ('lg_grade', models.FloatField(default=0)),
                ('waste_tonnes', models.FloatField(default=0)),
                ('total_mined_tonnes', models.FloatField(default=0)),
                ('weighted_mined_grade', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['period'],
            },
        ),
        migrations.CreateModel(
            name='MinePhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('csv_match_name', models.CharField(blank=True, help_text="The name used in the CSV file (e.g., 'macsluck'). If empty, uses the official name.", max_length=100)),
                ('pit', models.CharField(max_length=100)),
                ('phase_number', models.PositiveIntegerField()),
                ('sequence_order', models.PositiveIntegerField()),
                ('planned_start', models.DateField(blank=True, null=True)),
                ('planned_end', models.DateField(blank=True, null=True)),
                ('expected_grade', models.FloatField(blank=True, help_text='Expected average grade (g/t)', null=True)),
                ('expected_tonnage', models.FloatField(blank=True, help_text='Expected total tonnage (t)', null=True)),
            ],
            options={
                'ordering': ['sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyProductionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_period', models.CharField(help_text='Format YYYY-MM', max_length=7)),
                ('material_type', models.CharField(max_length=50)),
                ('available_tonnage', models.FloatField(help_text='Total mass from CSV for this month')),
                ('avg_grade', models.FloatField(help_text='Weighted average grade from CSV')),
                ('plant_target', models.FloatField(help_text='How much you WANT to process (e.g. 780t)')),
                ('sent_to_stockpile', models.FloatField(help_text='The remaining ore sent to stockpile')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('capacity_tph', models.FloatField(blank=True, help_text='Plant throughput capacity (tons per hour)', null=True)),
                ('default_grade', models.FloatField(blank=True, help_text='Default feed grade in g/t', null=True)),
                ('default_recovery', models.FloatField(blank=True, help_text='Default gold recovery fraction (e.g. 0.92 = 92%)', null=True)),
                ('default_gold_price', models.FloatField(blank=True, help_text='Default gold price per kg (USD)', null=True)),
            ],
            options={
                'verbose_name': 'Processing Plant',
                'verbose_name_plural': 'Processing Plants',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='mucs_2026', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Stockpile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('current_tonnage', models.FloatField(default=0)),
                ('projected_tonnage', models.FloatField(default=0)),
                ('grade', models.FloatField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OreSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sample_id', models.CharField(blank=True, max_length=100)),
                ('actual_grade_g_t', models.FloatField()),
                ('actual_tonnage', models.FloatField(default=0.0, help_text='Tonnage in tons')),
                ('expected_grade', models.FloatField()),
                ('expected_tonnage', models.FloatField()),
                ('mine_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ore_samples', to='dashboard.minephase')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mining_cost_per_tonne', models.FloatField(default=4.5)),
                ('physical_schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='dashboard.materialschedule')),
            ],
        ),
        migrations.CreateModel(
            name='PhaseSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_start', models.DateField(blank=True, null=True)),
                ('planned_end', models.DateField(blank=True, null=True)),
                ('planned_tonnage', models.FloatField(default=0)),
                ('removed_tonnage', models.FloatField(default=0)),
                ('current_progress', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('completed', 'Completed')], default='planned', max_length=20)),
                ('mine_phase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='dashboard.minephase')),
            ],
        ),
        migrations.CreateModel(
            name='PitBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_id', models.CharField(help_text="e.g., 'Ph1-Blk24'", max_length=50, unique=True)),
                ('x_position', models.IntegerField(default=0)),
                ('y_position', models.IntegerField(default=0)),
                ('target_tonnage', models.FloatField(default=5000)),
                ('removed_tonnage', models.FloatField(default=0)),
                ('grade', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('mined', 'Mined')], default='planned', max_length=20)),
                ('mine_phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='dashboard.minephase')),
            ],
        ),
        migrations.CreateModel(
            name='DailyProductionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tonnage_removed', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='dashboard.pitblock')),
            ],
        ),
        migrations.CreateModel(
            name='PlantDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('required_tonnage', models.FloatField()),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demands', to='dashboard.plant')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('tonnage', models.FloatField()),
                ('expected_tonnage', models.FloatField(blank=True, help_text='Planned tonnage for this batch', null=True)),
                ('material_type', models.CharField(choices=[('ore', 'Ore'), ('waste', 'Waste')], default='ore', max_length=20)),
                ('variance', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('grade', models.FloatField(blank=True, help_text='Grade in g/t', null=True)),
                ('recovery', models.FloatField(blank=True, help_text='Recovery fraction (0.9 = 90%)', null=True)),
                ('gold_price', models.FloatField(blank=True, help_text='Gold price per kg (USD)', null=True)),
                ('mine_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_records', to='dashboard.minephase')),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productions', to='dashboard.plant')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='materialschedule',
            name='scenario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='dashboard.schedulescenario'),
        ),
        migrations.CreateModel(
            name='FinancialSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold_price', models.FloatField(default=1800.0, help_text='USD per Ounce')),
                ('recovery_rate', models.FloatField(default=0.9, help_text='90% = 0.9')),
                ('plant_capacity', models.FloatField(default=23400.0, help_text='Monthly Plant Capacity (tonnes)')),
                ('processing_cost', models.FloatField(default=36.0, help_text='USD per Tonne')),
                ('base_mining_cost', models.FloatField(default=4.5, help_text='USD per Tonne (Base)')),
                ('scenario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financials', to='dashboard.schedulescenario')),
            ],
        ),
        migrations.CreateModel(
            name='StockpileState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mass', models.FloatField(default=0)),
                ('grade', models.FloatField(default=0)),
                ('physical_schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stockpile_state', to='dashboard.materialschedule')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodStockpileActual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.IntegerField()),
                ('hg_tonnage', models.FloatField(default=0, help_text='High Grade Stockpile Actual')),
                ('hg_grade', models.FloatField(default=0)),
                ('mg_tonnage', models.FloatField(default=0, help_text='Medium Grade Stockpile Actual')),
                ('mg_grade', models.FloatField(default=0)),
                ('lg_tonnage', models.FloatField(default=0, help_text='Low Grade Stockpile Actual')),
                ('lg_grade', models.FloatField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.schedulescenario')),
            ],
            options={
                'unique_together': {('scenario', 'period')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='materialschedule',
            unique_together={('scenario', 'period')},
        ),
    ]
