# Generated by Django 5.2.7 on 2025-10-17 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MinePhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pit', models.CharField(max_length=100)),
                ('phase_number', models.PositiveIntegerField()),
                ('sequence_order', models.PositiveIntegerField()),
                ('planned_start', models.DateField(blank=True, null=True)),
                ('planned_end', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='PlantDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('required_tonnage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Stockpile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('current_tonnage', models.FloatField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OreSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('sample_id', models.CharField(blank=True, max_length=100)),
                ('grade_g_t', models.FloatField()),
                ('mine_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ore_samples', to='dashboard.minephase')),
            ],
        ),
        migrations.CreateModel(
            name='PhaseSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_tonnage', models.FloatField(default=0)),
                ('removed_tonnage', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('completed', 'Completed')], default='planned', max_length=20)),
                ('mine_phase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='dashboard.minephase')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('tonnage', models.FloatField()),
                ('material_type', models.CharField(choices=[('ore', 'Ore'), ('waste', 'Waste')], default='ore', max_length=20)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('mine_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_records', to='dashboard.minephase')),
            ],
        ),
    ]
