# Generated by Django 5.2.7 on 2025-10-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phaseschedule',
            name='current_progress',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='phaseschedule',
            name='planned_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phaseschedule',
            name='planned_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
