# Generated by Django 5.2.7 on 2025-10-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_phaseschedule_current_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oresample',
            name='tonnage',
            field=models.FloatField(default=0.0),
        ),
    ]
