# Generated by Django 5.2.7 on 2025-10-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_oresample_tonnage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oresample',
            name='tonnage',
            field=models.FloatField(default=0.0, help_text='Tonnage in tons'),
        ),
    ]
