# Generated by Django 5.2.7 on 2025-10-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_oresample_tonnage'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockpile',
            name='grade',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockpile',
            name='projected_tonnage',
            field=models.FloatField(default=0),
        ),
    ]
