# Generated by Django 5.2.7 on 2025-11-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_stockpile_grade_stockpile_projected_tonnage'),
    ]

    operations = [
        migrations.AddField(
            model_name='minephase',
            name='expected_grade',
            field=models.FloatField(blank=True, help_text='Expected average grade (g/t)', null=True),
        ),
        migrations.AddField(
            model_name='minephase',
            name='expected_tonnage',
            field=models.FloatField(blank=True, help_text='Expected total tonnage (t)', null=True),
        ),
    ]
