# Generated by Django 5.2.7 on 2025-11-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_minephase_expected_grade_minephase_expected_tonnage'),
    ]

    operations = [
        migrations.AddField(
            model_name='oresample',
            name='expected_grade',
            field=models.FloatField(default=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oresample',
            name='expected_tonnage',
            field=models.FloatField(default=45),
            preserve_default=False,
        ),
    ]
