# Generated by Django 5.2.7 on 2025-11-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_oresample_expected_grade_oresample_expected_tonnage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oresample',
            old_name='tonnage',
            new_name='actual_tonnage',
        ),
        migrations.RemoveField(
            model_name='oresample',
            name='grade_g_t',
        ),
        migrations.AddField(
            model_name='oresample',
            name='actual_grade_g_t',
            field=models.FloatField(default=30),
            preserve_default=False,
        ),
    ]
