# Generated by Django 5.2.7 on 2025-11-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_rename_tonnage_oresample_actual_tonnage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oresample',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
