# Generated by Django 5.2.7 on 2025-11-10 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_oresample_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('capacity_tph', models.FloatField(blank=True, help_text='Capacity in tons per hour', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='productionrecord',
            name='expected_tonnage',
            field=models.FloatField(blank=True, help_text='Planned tonnage for this batch', null=True),
        ),
        migrations.AddField(
            model_name='plantdemand',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demands', to='dashboard.plant'),
        ),
        migrations.AddField(
            model_name='productionrecord',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productions', to='dashboard.plant'),
        ),
    ]
