# Generated by Django 5.2.7 on 2025-11-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_plant_productionrecord_expected_tonnage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionrecord',
            name='variance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
