# Generated by Django 5.2.7 on 2025-11-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_productionrecord_variance'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionrecord',
            name='status',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
