# Generated by Django 5.2.7 on 2025-11-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_productionrecord_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plant',
            options={'ordering': ['name'], 'verbose_name': 'Processing Plant', 'verbose_name_plural': 'Processing Plants'},
        ),
        migrations.AlterModelOptions(
            name='productionrecord',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='plant',
            name='default_gold_price',
            field=models.FloatField(blank=True, help_text='Default gold price per kg (USD)', null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='default_grade',
            field=models.FloatField(blank=True, help_text='Default feed grade in g/t', null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='default_recovery',
            field=models.FloatField(blank=True, help_text='Default gold recovery fraction (e.g. 0.92 = 92%)', null=True),
        ),
        migrations.AddField(
            model_name='productionrecord',
            name='gold_price',
            field=models.FloatField(blank=True, help_text='Gold price per kg (USD)', null=True),
        ),
        migrations.AddField(
            model_name='productionrecord',
            name='grade',
            field=models.FloatField(blank=True, help_text='Grade in g/t', null=True),
        ),
        migrations.AddField(
            model_name='productionrecord',
            name='recovery',
            field=models.FloatField(blank=True, help_text='Recovery fraction (0.9 = 90%)', null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='capacity_tph',
            field=models.FloatField(blank=True, help_text='Plant throughput capacity (tons per hour)', null=True),
        ),
    ]
