# Generated by Django 5.2.7 on 2026-01-16 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_plant_options_alter_productionrecord_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='mucs_2026', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.IntegerField(help_text='Period Number (e.g., 1, 2, 3)')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('material_type', models.CharField(choices=[('waste', 'Waste'), ('low_grade', 'Low Grade'), ('medium_grade', 'Medium Grade'), ('high_grade', 'High Grade')], max_length=50)),
                ('volume', models.FloatField(default=0, help_text='Volume in cubic meters')),
                ('mass', models.FloatField(default=0, help_text='Mass in tonnes')),
                ('haul_distance', models.FloatField(default=0, help_text='Haulage length in meters')),
                ('grade', models.FloatField(default=0, help_text='Average aggregate grade')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='dashboard.schedulescenario')),
            ],
            options={
                'ordering': ['period', 'material_type'],
            },
        ),
    ]
