# Generated by Django 5.2.7 on 2026-01-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_schedulescenario_materialschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialschedule',
            name='phase_name',
            field=models.CharField(blank=True, help_text="e.g., 'Phase 1' or 'Pushback A'", max_length=100, null=True),
        ),
    ]
