# Generated by Django 5.2.7 on 2026-01-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_materialschedule_phase_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialschedule',
            name='fleet',
            field=models.CharField(blank=True, help_text='e.g. fleet1, load_and_haul', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='materialschedule',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Stores extra CSV columns like Activity, Aggregate, etc.'),
        ),
        migrations.AlterField(
            model_name='materialschedule',
            name='grade',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='materialschedule',
            name='haul_distance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='materialschedule',
            name='mass',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='materialschedule',
            name='phase_name',
            field=models.CharField(blank=True, help_text="e.g., 'Phase 1' or 'mucs_luck_pit'", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='materialschedule',
            name='volume',
            field=models.FloatField(default=0),
        ),
    ]
