# Generated by Django 5.2.7 on 2026-01-23 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_materialschedule_fleet_materialschedule_metadata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyProductionTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.DateField(help_text='The first day of the month this target applies to')),
                ('material_class', models.CharField(help_text='e.g. High Grade, Low Grade', max_length=50)),
                ('planned_tonnage', models.FloatField(default=0.0)),
                ('planned_grade', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-month_year'],
                'unique_together': {('month_year', 'material_class')},
            },
        ),
    ]
