# Generated by Django 5.2.7 on 2026-01-23 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_monthlyproductiontarget'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonthlyProductionTarget',
        ),
    ]
