# Generated by Django 5.2.7 on 2026-01-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_delete_monthlyproductiontarget'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyProductionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_period', models.CharField(help_text='Format YYYY-MM', max_length=7)),
                ('material_type', models.CharField(max_length=50)),
                ('available_tonnage', models.FloatField(help_text='Total mass from CSV for this month')),
                ('avg_grade', models.FloatField(help_text='Weighted average grade from CSV')),
                ('plant_target', models.FloatField(help_text='How much you WANT to process (e.g. 780t)')),
                ('sent_to_stockpile', models.FloatField(help_text='The remaining ore sent to stockpile')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
