# Generated by Django 5.2.7 on 2026-01-31 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_monthlyproductionplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulescenario',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
