# Generated by Django 5.2.7 on 2026-01-31 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_schedulescenario_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='minephase',
            name='csv_match_name',
            field=models.CharField(blank=True, help_text="The name used in the CSV file (e.g., 'macsluck'). If empty, uses the official name.", max_length=100),
        ),
    ]
