# Generated by Django 5.2.7 on 2026-01-31 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_minephase_csv_match_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold_price', models.FloatField(default=1800.0, help_text='USD per Ounce')),
                ('recovery_rate', models.FloatField(default=0.9, help_text='90% = 0.9')),
                ('plant_capacity', models.FloatField(default=23400.0, help_text='Monthly Plant Capacity (tonnes)')),
                ('processing_cost', models.FloatField(default=36.0, help_text='USD per Tonne')),
                ('base_mining_cost', models.FloatField(default=4.5, help_text='USD per Tonne (Base)')),
                ('scenario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financials', to='dashboard.schedulescenario')),
            ],
        ),
    ]
