# Generated by Django 5.2.7 on 2026-02-02 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_financialsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='PitBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_id', models.CharField(help_text="e.g., 'Ph1-Blk24'", max_length=50, unique=True)),
                ('x_position', models.IntegerField(default=0)),
                ('y_position', models.IntegerField(default=0)),
                ('target_tonnage', models.FloatField(default=5000)),
                ('removed_tonnage', models.FloatField(default=0)),
                ('grade', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('mined', 'Mined')], default='planned', max_length=20)),
                ('mine_phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='dashboard.minephase')),
            ],
        ),
        migrations.CreateModel(
            name='DailyProductionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tonnage_removed', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='dashboard.pitblock')),
            ],
        ),
    ]
