# Generated by Django 5.2.7 on 2026-02-03 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_pitblock_dailyproductionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodStockpileActual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.IntegerField()),
                ('hg_tonnage', models.FloatField(default=0, help_text='High Grade Stockpile Actual')),
                ('hg_grade', models.FloatField(default=0)),
                ('mg_tonnage', models.FloatField(default=0, help_text='Medium Grade Stockpile Actual')),
                ('mg_grade', models.FloatField(default=0)),
                ('lg_tonnage', models.FloatField(default=0, help_text='Low Grade Stockpile Actual')),
                ('lg_grade', models.FloatField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.schedulescenario')),
            ],
            options={
                'unique_together': {('scenario', 'period')},
            },
        ),
    ]
