# Generated by Django 5.2.7 on 2026-02-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_periodstockpileactual'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPlantFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('tonnes_fed', models.FloatField(help_text='Tonnes supplied to plant today')),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
